print("Hello! How are you doing?")
feelpast = input()
#make habit
print("I hope you are feeling well! I'm your new habit tracker! I help you make a checklist what you want to do to do a habit daily and stop a bad habit! \n First, let's make a habit! What activity would you like to make a habit? Only one please.")
habit = input()
print("Ok! How frequently do you want to do " , habit , "? Put the number of times a day you want to do it.")
time = input()
print("Do you think you are doing well on your " , habit , "? Bad, good, great, or awesome?")
well = input()
print("Why do you feel that you are doing " , well , " on " , habit , "?")
whywell = input()
print("What do you think you need to do to complete " , habit , "?")
plan = input()
#bad habit
print("Next, let's make a plan to stop a bad habit! \n What bad habit would you like to stop?")
badhabit = input()
print("Why do you want to stop " , badhabit , "?")
badreason = input()
print("What do you think would stop " , badhabit , "?")
badplan = input()
print("Ok! Thank you for filling this out! Now I will tell you your plan!")
print("A new habit you want to make is " , habit , " and to complete that you will" , plan , "" , time , " times a day. For your bad habit, you want to stop " , badhabit , " because " , badreason , ". You will stop this by " , badplan , ".")
